# states.py یا conversation_states.py

WAITING_FOR_PRODUCT_NAME = 1
WAITING_FOR_PRODUCT_PRICE = 2
WAITING_FOR_CATEGORY_SELECTION = 3
WAITING_FOR_CONFIRMATION = 4
WAITING_FOR_EDIT_PRODUCT_NAME = 5
WAITING_FOR_EDIT_PRODUCT_PRICE = 6
WAITING_FOR_EDIT_CATEGORY_SELECTION = 7
WAITING_FOR_SEARCH_PRODUCT = 8

EDIT_NAME, EDIT_PRICE, EDIT_CATEGORY = range(3)
